// Spacenet Network — catalog data
const CATEGORIES = [
  { id: "airframes",   label: "Airframes & Structures",       icon: "frame" },
  { id: "propulsion",  label: "Propulsion & Microjet Engines", icon: "turbine" },
  { id: "avionics",    label: "Flight Control & Avionics",     icon: "avionics" },
  { id: "sensors",     label: "Sensors & Payload Systems",     icon: "sensor" },
  { id: "power",       label: "Power Systems",                 icon: "battery" },
  { id: "comms",       label: "Communications & Datalink",     icon: "antenna" },
];

const CONTACT = {
  telegram: "https://t.me/g64group",
  telegramHandle: "@g64group",
  whatsapp: "https://wa.me/918073293264",
  whatsappDisplay: "+91 80732 93264",
};

const PRODUCTS = [
  { sku: "SPN-AF-1001", name: "220mm Carbon Racing Frame", category: "airframes", icon: "frame", image: "img/frame-220.jpg",
    specs: [["Wheelbase","220 mm"],["Material","3K carbon fiber"],["Weight","98 g"],["Arms","4, quick-swap"]],
    price: "$64.00", blurb: "Lightweight quad frame for FPV and light multirotor builds." },
  { sku: "SPN-AF-1014", name: "Hexacopter Heavy-Lift Frame", category: "airframes", icon: "frame", image: "img/frame-hexa.jpg",
    specs: [["Wheelbase","960 mm"],["Material","Carbon/aluminum hybrid"],["Payload capacity","9.5 kg"],["Arms","6, folding"]],
    price: "$389.00", blurb: "Folding hexacopter chassis rated for survey and heavy-payload work." },
  { sku: "SPN-AF-1027", name: "Fixed-Wing Airframe Kit, 1.8 m", category: "airframes", icon: "frame", image: "img/frame-fw.jpg",
    specs: [["Wingspan","1.8 m"],["Material","EPO foam / carbon spar"],["Max takeoff weight","4.2 kg"],["Wing loading","38 g/dm²"]],
    price: "$310.00", blurb: "Long-endurance fixed-wing kit for mapping and ISR-class payloads." },
  { sku: "SPN-AF-1042", name: "Retractable Landing Gear Set", category: "airframes", icon: "frame", image: "img/frame-hexa.jpg",
    specs: [["Actuation","Electric, 12V"],["Ground clearance","140 mm"],["Load rating","6 kg"],["Retract time","1.4 s"]],
    price: "$118.00", blurb: "Servoless electric retracts for gimbal-equipped airframes." },

  { sku: "SPN-PR-2003", name: "Brushless Motor 2216, 900KV", category: "propulsion", icon: "turbine", image: "img/motor.jpg",
    specs: [["KV","900"],["Max thrust","1.6 kgf"],["Voltage","3–6S"],["Weight","68 g"]],
    price: "$22.50", blurb: "General-purpose outrunner for small to mid-frame multirotors." },
  { sku: "SPN-PR-2019", name: "Micro Turbojet Engine, 180N", category: "propulsion", icon: "turbine", image: "img/jet-180.jpg",
    specs: [["Thrust","180 N (18.4 kgf)"],["Fuel","Jet-A1 / kerosene"],["EGT limit","720 °C"],["Dry weight","1.1 kg"]],
    price: "$3,450.00", blurb: "Turboshaft-derived microjet for fixed-wing target and demonstrator platforms. Export-controlled — end-use certificate required.",
    exportControlled: true },
  { sku: "SPN-PR-2024", name: "Micro Turbojet Engine, 320N", category: "propulsion", icon: "turbine", image: "img/jet-320.jpg",
    specs: [["Thrust","320 N (32.6 kgf)"],["Fuel","Jet-A1 / kerosene"],["EGT limit","740 °C"],["Dry weight","2.3 kg"]],
    price: "$6,900.00", blurb: "Higher-thrust microjet for larger tactical and research airframes. Export-controlled — end-use certificate required.",
    exportControlled: true },
  { sku: "SPN-PR-2031", name: "Folding Carbon Propeller, 15×5.5", category: "propulsion", icon: "turbine", image: "img/prop.jpg",
    specs: [["Diameter","15 in"],["Pitch","5.5 in"],["Material","Carbon-nylon"],["Hub bore","8 mm"]],
    price: "$14.00", blurb: "Folding prop pair for fixed-wing and VTOL propulsion." },

  { sku: "SPN-AV-3005", name: "Flight Controller, F7 Dual-IMU", category: "avionics", icon: "avionics", image: "img/fc-f7.jpg",
    specs: [["MCU","STM32F7"],["IMU","Dual, vibration-isolated"],["Firmware","ArduPilot / PX4"],["I/O","14× PWM, 6× UART"]],
    price: "$89.00", blurb: "General-purpose autopilot board supporting open-source firmware stacks." },
  { sku: "SPN-AV-3012", name: "Mission Computer, ARM Octa-Core", category: "avionics", icon: "avionics", image: "img/companion.jpg",
    specs: [["CPU","8-core ARM, 2.4 GHz"],["RAM","8 GB"],["Interfaces","Ethernet, CAN, MIPI-CSI"],["Power","5–20V in"]],
    price: "$540.00", blurb: "Companion computer for onboard vision, autonomy, and payload tasking." },
  { sku: "SPN-AV-3020", name: "ESC, 4-in-1 60A BLHeli32", category: "avionics", icon: "avionics", image: "img/esc.jpg",
    specs: [["Current per motor","60A cont."],["Protocol","DShot600"],["Voltage","3–8S"],["Telemetry","Yes"]],
    price: "$58.00", blurb: "Compact quad ESC stack with per-motor current telemetry." },

  { sku: "SPN-SN-4002", name: "3-Axis Gimbal, EO/IR Payload", category: "sensors", icon: "sensor", image: "img/gimbal.jpg",
    specs: [["Payload capacity","1.2 kg"],["Stabilization","3-axis brushless"],["Sensors","EO 30x zoom + IR"],["Weight","780 g"]],
    price: "$2,150.00", blurb: "Stabilized gimbal for daylight and thermal observation payloads." },
  { sku: "SPN-SN-4010", name: "LiDAR Module, 100 m Range", category: "sensors", icon: "sensor", image: "img/lidar.jpg",
    specs: [["Range","100 m"],["Points/sec","320,000"],["Accuracy","±2 cm"],["Weight","165 g"]],
    price: "$1,480.00", blurb: "Survey-grade LiDAR for mapping, inspection, and terrain-following." },
  { sku: "SPN-SN-4021", name: "Multispectral Camera, 5-Band", category: "sensors", icon: "sensor", image: "img/mspec.jpg",
    specs: [["Bands","5, incl. NIR/Red-edge"],["Resolution","1.2 MP/band"],["Trigger","GPS-synced"],["Weight","215 g"]],
    price: "$3,200.00", blurb: "Agricultural and environmental survey payload with synced multi-band capture." },
  { sku: "SPN-SN-4033", name: "Radar Altimeter, 0.3–500 m", category: "sensors", icon: "sensor", image: "img/radar.jpg",
    specs: [["Range","0.3–500 m"],["Update rate","20 Hz"],["Interface","UART/CAN"],["Weight","42 g"]],
    price: "$620.00", blurb: "Low-latency height-above-ground sensor for terrain-following flight." },

  { sku: "SPN-PW-5004", name: "LiPo Battery, 6S 10000mAh", category: "power", icon: "battery", image: "img/lipo.jpg",
    specs: [["Capacity","10,000 mAh"],["Voltage","6S / 22.2V"],["Discharge","25C cont."],["Weight","1.35 kg"]],
    price: "$210.00", blurb: "High-capacity pack for heavy-lift and long-endurance flights." },
  { sku: "SPN-PW-5011", name: "Power Distribution Board, 12S", category: "power", icon: "battery", image: "img/pdb.jpg",
    specs: [["Max voltage","12S / 50.4V"],["Continuous current","400A"],["Outputs","8× motor, 4× aux"],["Weight","44 g"]],
    price: "$36.00", blurb: "High-current PDB for multi-motor heavy-lift platforms." },
  { sku: "SPN-PW-5018", name: "Hybrid Generator, 1.2kW", category: "power", icon: "battery", image: "img/jet-180.jpg",
    specs: [["Output","1.2 kW cont."],["Fuel","Gasoline, 2-stroke"],["Weight","3.4 kg"],["Runtime","4.5 hr @ 15L"]],
    price: "$1,890.00", blurb: "Onboard generator for extended-endurance hybrid-electric platforms." },

  { sku: "SPN-CM-6006", name: "Datalink Radio, 15km LOS", category: "comms", icon: "antenna", image: "img/datalink.jpg",
    specs: [["Range","15 km LOS"],["Frequency","2.4 GHz"],["Latency","<20 ms"],["Encryption","AES-256"]],
    price: "$680.00", blurb: "Encrypted command-and-telemetry link for BVLOS operations." },
  { sku: "SPN-CM-6013", name: "RTK GPS Module, Dual-Band", category: "comms", icon: "antenna", image: "img/rtk.jpg",
    specs: [["Accuracy","1 cm + 1 ppm"],["Bands","L1/L2/L5"],["Update rate","10 Hz"],["Weight","28 g"]],
    price: "$245.00", blurb: "Centimeter-accurate positioning for precision navigation and landing." },
  { sku: "SPN-CM-6020", name: "Video Transmitter, 5.8GHz 2W", category: "comms", icon: "antenna", image: "img/vtx.jpg",
    specs: [["Power output","2 W"],["Frequency","5.8 GHz"],["Channels","40"],["Weight","31 g"]],
    price: "$52.00", blurb: "Long-range analog/digital video downlink transmitter." },
];
